# Generated by Django 3.2.6 on 2021-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_vk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkmsg',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
