# Generated by Django 3.2.6 on 2021-08-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tg', '0003_tgmsg_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmsg',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
